@echo off
echo Starting Gradio application in WSL...
start wsl bash -c "cd /mnt/d/train/qwen3_clothing_classifier && source venv_wsl/bin/activate && python3 app.py"
echo Waiting for server to start...
timeout /t 15 /nobreak
echo Opening browser...
start http://localhost:7860
